
import { GoogleGenAI } from "@google/genai";

const MODEL_NAME = 'gemini-2.5-flash-image';

export const generateTifo = async (base64Image: string, teamName: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Clean base64 string (remove data:image/...;base64,)
  const imageData = base64Image.split(',')[1];
  
  const prompt = `
    A high-quality wide-angle cinematic shot of a professional football stadium packed with thousands of fans at night under bright floodlights. 
    In the main grandstand, the supporters are holding up thousands of colored square panels to form a massive, detailed mosaic (tifo). 
    The mosaic should clearly feature the person from the provided image, but stylized as a supporter-made pixel-art tifo mosaic.
    The colors of the fans' clothes, flags, and stadium decorations should predominantly be the national colors of ${teamName}.
    The atmosphere is electric with smoke flares in the distance. 
    This is for a professional social media cover photo. Ultra-realistic, 8k resolution.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: imageData,
              mimeType: 'image/jpeg',
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9",
        },
      },
    });

    let imageUrl = '';
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
